

services:
  microblog:
    build:
      context: .            # 构建上下文：项目根目录
      dockerfile: Dockerfile
    image: flask-microblog
    command: ["gunicorn", "microblog:app", "--bind", "0.0.0.0:5000", "--workers", "2"]
    ports:
      - "8000:5000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      microblog-network:
        aliases:
          - elasticsearch


    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/flask.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - microblog
    networks:
      - microblog-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - microblog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microblog-network


networks:
  microblog-network:


volumes:
  db-data:
  es-data:


