"""add language to posts

Revision ID: 544bbaad8db5
Revises: 83b8564af21e
Create Date: 2025-06-29 16:14:14.727661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544bbaad8db5'
down_revision = '83b8564af21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
